### ISSUE TITLE
P2 js 变量使用更有意义的变量名

### ISSUE THREAD

**Issue by EthanLin-TWer** [udacity/cn-frontend-development-advanced#9]
`Website Optimization_zh/js/perfmatters.js` 文件中：

```js
4 function logCRP() {
5   var t = window.performance.timing,
6     dcl = t.domContentLoadedEventStart - t.domLoading,
7     complete = t.domComplete - t.domLoading;
8   var stats = document.getElementById("crp-stats");
9   stats.textContent = 'DCL: ' + dcl + 'ms, onload: ' + complete + 'ms';
10 }
```

* `t` 建议重命名为 `timing`
* `dcl` 建议重命名为 `domContentLoadedDuration`
* `complete` 建议重命名为 `domCompleteDuration`

`Website Optimization_zh/views/js/main.js` 文件中：

```js
520 // 当页面加载时生成披萨滑窗
521 document.addEventListener('DOMContentLoaded', function() {
522   var cols = 8;
523   var s = 256;
524   ...
```

在这里：http://discussions.youdaxue.com/t/topic/38793 ，阿权同学提到说 `s` 其实是 pizza 大小的意思，因此我建议这个变量也重命名成更有表达力的名字。不过因为我还没看到和运行这块代码，我也不知道这个变量名改成什么更好，坐等其他同学建议，或者等我做到了项目研究研究。

用表意的变量名，目标是使读代码就像读文章一样，有一致的抽象层级，不需深入细节也可知道代码做了什么事。

我正在提 PR~

**Comment by PoBlue** [comment]
@linesh-simplicity 赶快赶紧做这个项目～

**Comment by caochenwei** [comment]
fixed
